services:
  app:
    image: node:22-alpine
    container_name: subway-alert-b
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
    env_file:
      - ./.env
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SEOUL_METRO_REALTIME_URL: ${SEOUL_METRO_REALTIME_URL}
      PROFILE: ${PROFILE}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./:/app
      - ./data:/app/data
      - subway_alert_node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  subway_alert_node_modules: